/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as BenchmarkRouteImport } from './routes/benchmark'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WarehouseManagementRouteImport } from './routes/warehouse-management'
import { Route as WarehouseIndexRouteImport } from './routes/warehouse/index'
import { Route as WarehouseAddInventoryRouteImport } from './routes/warehouse/add-inventory'
import { Route as WarehouseHistoryRouteImport } from './routes/warehouse/history'
import { Route as WarehouseInventoryRouteImport } from './routes/warehouse/inventory'
import { Route as WarehouseProfileRouteImport } from './routes/warehouse/profile'
import { Route as WarehouseTransferRequestsRouteImport } from './routes/warehouse/transfer-requests'
import { Route as WarehouseUploadRouteImport } from './routes/warehouse/upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarkRoute = BenchmarkRouteImport.update({
  id: '/benchmark',
  path: '/benchmark',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseManagementRoute = WarehouseManagementRouteImport.update({
  id: '/warehouse-management',
  path: '/warehouse-management',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseIndexRoute = WarehouseIndexRouteImport.update({
  id: '/warehouse/',
  path: '/warehouse/',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseAddInventoryRoute = WarehouseAddInventoryRouteImport.update({
  id: '/warehouse/add-inventory',
  path: '/warehouse/add-inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseHistoryRoute = WarehouseHistoryRouteImport.update({
  id: '/warehouse/history',
  path: '/warehouse/history',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseInventoryRoute = WarehouseInventoryRouteImport.update({
  id: '/warehouse/inventory',
  path: '/warehouse/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseProfileRoute = WarehouseProfileRouteImport.update({
  id: '/warehouse/profile',
  path: '/warehouse/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseTransferRequestsRoute =
  WarehouseTransferRequestsRouteImport.update({
    id: '/warehouse/transfer-requests',
    path: '/warehouse/transfer-requests',
    getParentRoute: () => rootRouteImport,
  } as any)
const WarehouseUploadRoute = WarehouseUploadRouteImport.update({
  id: '/warehouse/upload',
  path: '/warehouse/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/benchmark': typeof BenchmarkRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/settings': typeof SettingsRoute
  '/warehouse-management': typeof WarehouseManagementRoute
  '/warehouse/add-inventory': typeof WarehouseAddInventoryRoute
  '/warehouse/history': typeof WarehouseHistoryRoute
  '/warehouse/inventory': typeof WarehouseInventoryRoute
  '/warehouse/profile': typeof WarehouseProfileRoute
  '/warehouse/transfer-requests': typeof WarehouseTransferRequestsRoute
  '/warehouse/upload': typeof WarehouseUploadRoute
  '/warehouse/': typeof WarehouseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/benchmark': typeof BenchmarkRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/settings': typeof SettingsRoute
  '/warehouse-management': typeof WarehouseManagementRoute
  '/warehouse/add-inventory': typeof WarehouseAddInventoryRoute
  '/warehouse/history': typeof WarehouseHistoryRoute
  '/warehouse/inventory': typeof WarehouseInventoryRoute
  '/warehouse/profile': typeof WarehouseProfileRoute
  '/warehouse/transfer-requests': typeof WarehouseTransferRequestsRoute
  '/warehouse/upload': typeof WarehouseUploadRoute
  '/warehouse': typeof WarehouseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/benchmark': typeof BenchmarkRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/settings': typeof SettingsRoute
  '/warehouse-management': typeof WarehouseManagementRoute
  '/warehouse/add-inventory': typeof WarehouseAddInventoryRoute
  '/warehouse/history': typeof WarehouseHistoryRoute
  '/warehouse/inventory': typeof WarehouseInventoryRoute
  '/warehouse/profile': typeof WarehouseProfileRoute
  '/warehouse/transfer-requests': typeof WarehouseTransferRequestsRoute
  '/warehouse/upload': typeof WarehouseUploadRoute
  '/warehouse/': typeof WarehouseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/analytics'
    | '/approvals'
    | '/audit'
    | '/benchmark'
    | '/inventory'
    | '/login'
    | '/profile'
    | '/recommendations'
    | '/settings'
    | '/warehouse-management'
    | '/warehouse/add-inventory'
    | '/warehouse/history'
    | '/warehouse/inventory'
    | '/warehouse/profile'
    | '/warehouse/transfer-requests'
    | '/warehouse/upload'
    | '/warehouse/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/analytics'
    | '/approvals'
    | '/audit'
    | '/benchmark'
    | '/inventory'
    | '/login'
    | '/profile'
    | '/recommendations'
    | '/settings'
    | '/warehouse-management'
    | '/warehouse/add-inventory'
    | '/warehouse/history'
    | '/warehouse/inventory'
    | '/warehouse/profile'
    | '/warehouse/transfer-requests'
    | '/warehouse/upload'
    | '/warehouse'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/analytics'
    | '/approvals'
    | '/audit'
    | '/benchmark'
    | '/inventory'
    | '/login'
    | '/profile'
    | '/recommendations'
    | '/settings'
    | '/warehouse-management'
    | '/warehouse/add-inventory'
    | '/warehouse/history'
    | '/warehouse/inventory'
    | '/warehouse/profile'
    | '/warehouse/transfer-requests'
    | '/warehouse/upload'
    | '/warehouse/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AuditRoute: typeof AuditRoute
  BenchmarkRoute: typeof BenchmarkRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RecommendationsRoute: typeof RecommendationsRoute
  SettingsRoute: typeof SettingsRoute
  WarehouseManagementRoute: typeof WarehouseManagementRoute
  WarehouseAddInventoryRoute: typeof WarehouseAddInventoryRoute
  WarehouseHistoryRoute: typeof WarehouseHistoryRoute
  WarehouseInventoryRoute: typeof WarehouseInventoryRoute
  WarehouseProfileRoute: typeof WarehouseProfileRoute
  WarehouseTransferRequestsRoute: typeof WarehouseTransferRequestsRoute
  WarehouseUploadRoute: typeof WarehouseUploadRoute
  WarehouseIndexRoute: typeof WarehouseIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmark': {
      id: '/benchmark'
      path: '/benchmark'
      fullPath: '/benchmark'
      preLoaderRoute: typeof BenchmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse-management': {
      id: '/warehouse-management'
      path: '/warehouse-management'
      fullPath: '/warehouse-management'
      preLoaderRoute: typeof WarehouseManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse/': {
      id: '/warehouse/'
      path: '/warehouse'
      fullPath: '/warehouse/'
      preLoaderRoute: typeof WarehouseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse/add-inventory': {
      id: '/warehouse/add-inventory'
      path: '/warehouse/add-inventory'
      fullPath: '/warehouse/add-inventory'
      preLoaderRoute: typeof WarehouseAddInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse/history': {
      id: '/warehouse/history'
      path: '/warehouse/history'
      fullPath: '/warehouse/history'
      preLoaderRoute: typeof WarehouseHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse/inventory': {
      id: '/warehouse/inventory'
      path: '/warehouse/inventory'
      fullPath: '/warehouse/inventory'
      preLoaderRoute: typeof WarehouseInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse/profile': {
      id: '/warehouse/profile'
      path: '/warehouse/profile'
      fullPath: '/warehouse/profile'
      preLoaderRoute: typeof WarehouseProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse/transfer-requests': {
      id: '/warehouse/transfer-requests'
      path: '/warehouse/transfer-requests'
      fullPath: '/warehouse/transfer-requests'
      preLoaderRoute: typeof WarehouseTransferRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse/upload': {
      id: '/warehouse/upload'
      path: '/warehouse/upload'
      fullPath: '/warehouse/upload'
      preLoaderRoute: typeof WarehouseUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApprovalsRoute: ApprovalsRoute,
  AuditRoute: AuditRoute,
  BenchmarkRoute: BenchmarkRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RecommendationsRoute: RecommendationsRoute,
  SettingsRoute: SettingsRoute,
  WarehouseManagementRoute: WarehouseManagementRoute,
  WarehouseAddInventoryRoute: WarehouseAddInventoryRoute,
  WarehouseHistoryRoute: WarehouseHistoryRoute,
  WarehouseInventoryRoute: WarehouseInventoryRoute,
  WarehouseProfileRoute: WarehouseProfileRoute,
  WarehouseTransferRequestsRoute: WarehouseTransferRequestsRoute,
  WarehouseUploadRoute: WarehouseUploadRoute,
  WarehouseIndexRoute: WarehouseIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
